name: Update vscode-icons

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    uses: catppuccin/actions/.github/workflows/vscode-icons.yml@v1
    with:
      path: vscode-icons
    secrets: inherit
